"""add purchase receipt

Revision ID: 0b3eafe3ce34
Revises: 8aca85ee91de
Create Date: 2026-06-28 18:43:45.632052

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b3eafe3ce34'
down_revision = '8aca85ee91de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('purchase_receipt_header',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('receipt_date', sa.Date(), nullable=False),
    sa.Column('vendor_id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('invoice_no', sa.String(length=100), nullable=True),
    sa.Column('invoice_date', sa.Date(), nullable=True),
    sa.Column('remarks', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['location_id'], ['location_master.id'], ),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendor_master.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('purchase_receipt_detail',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('purchase_receipt_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('qty', sa.Float(), nullable=False),
    sa.Column('rate', sa.Float(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['item_master.id'], ),
    sa.ForeignKeyConstraint(['purchase_receipt_id'], ['purchase_receipt_header.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('purchase_receipt_detail')
    op.drop_table('purchase_receipt_header')
    # ### end Alembic commands ###
