"""reverted to 20.07.2026

Revision ID: 0be85d51eb97
Revises: f5e5bb936f56
Create Date: 2026-07-22 23:28:24.979453

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0be85d51eb97'
down_revision = 'f5e5bb936f56'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    

    with op.batch_alter_table('job_work_header', schema=None) as batch_op:
        batch_op.drop_column('is_draft')

    

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    

    with op.batch_alter_table('job_work_header', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_draft', sa.BOOLEAN(), server_default=sa.text("'1'"), nullable=False))

    

    # ### end Alembic commands ###
