"""add stock adjustment

Revision ID: 0c7bc80b2e2c
Revises: df5500c7cd08
Create Date: 2026-06-28 17:31:29.502511

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c7bc80b2e2c'
down_revision = 'df5500c7cd08'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stock_adjustment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('adjustment_date', sa.Date(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('remarks', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['location_id'], ['location_master.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stock_adjustment_detail',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stock_adjustment_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('adjustment_type', sa.String(length=20), nullable=False),
    sa.Column('qty', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['item_master.id'], ),
    sa.ForeignKeyConstraint(['stock_adjustment_id'], ['stock_adjustment.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stock_adjustment_detail')
    op.drop_table('stock_adjustment')
    # ### end Alembic commands ###
