"""Added Receiving Note Detail

Revision ID: 191c63f41e22
Revises: 62434d92effe
Create Date: 2026-07-10 01:33:27.996248

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '191c63f41e22'
down_revision = '62434d92effe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('receiving_note_detail',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('receiving_note_header_id', sa.Integer(), nullable=False),
    sa.Column('sales_invoice_detail_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('dispatch_qty', sa.Float(), nullable=False),
    sa.Column('received_qty', sa.Float(), nullable=True),
    sa.Column('rejected_qty', sa.Float(), nullable=True),
    sa.Column('short_qty', sa.Float(), nullable=True),
    sa.Column('remarks', sa.String(length=300), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['item_master.id'], ),
    sa.ForeignKeyConstraint(['receiving_note_header_id'], ['receiving_note_header.id'], ),
    sa.ForeignKeyConstraint(['sales_invoice_detail_id'], ['sales_invoice_detail.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    op.drop_table('receiving_note_detail')
    # ### end Alembic commands ###
