"""add totals to purchase receipt header

Revision ID: 1bc7297642a8
Revises: ec130b402adf
Create Date: 2026-06-28 21:34:52.049702

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1bc7297642a8'
down_revision = 'ec130b402adf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('purchase_receipt_header', schema=None) as batch_op:
        batch_op.add_column(sa.Column('basic_amount', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('gst_amount', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('invoice_amount', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('purchase_receipt_header', schema=None) as batch_op:
        batch_op.drop_column('invoice_amount')
        batch_op.drop_column('gst_amount')
        batch_op.drop_column('basic_amount')

    # ### end Alembic commands ###
