"""add job work detail

Revision ID: 258c585a4081
Revises: 38fc44031698
Create Date: 2026-07-20 23:31:19.742997

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '258c585a4081'
down_revision = '38fc44031698'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_work_detail',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_work_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('line_type', sa.String(length=20), nullable=False),
    sa.Column('expected_qty', sa.Float(), nullable=True),
    sa.Column('actual_qty', sa.Float(), nullable=True),
    sa.Column('rate', sa.Float(), nullable=True),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('remarks', sa.String(length=250), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['item_master.id'], ),
    sa.ForeignKeyConstraint(['job_work_id'], ['job_work_header.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    

    op.drop_table('job_work_detail')
    # ### end Alembic commands ###
