"""Added Transporter Master

Revision ID: 27087b17c8dd
Revises: 549845b790b4
Create Date: 2026-07-05 11:09:31.525772

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27087b17c8dd'
down_revision = '549845b790b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    '''op.create_table('transporter_master',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transporter_code', sa.String(length=20), nullable=False),
    sa.Column('transporter_name', sa.String(length=200), nullable=False),
    sa.Column('contact_person', sa.String(length=100), nullable=True),
    sa.Column('mobile_no', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('gstin', sa.String(length=20), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('transporter_code')
    )
    with op.batch_alter_table('customer_po_detail', schema=None) as batch_op:
        batch_op.alter_column('item_id',
               existing_type=sa.INTEGER(),
               nullable=False)'''
    
    pass

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customer_po_detail', schema=None) as batch_op:
        batch_op.alter_column('item_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    op.drop_table('transporter_master')
    # ### end Alembic commands ###
