"""Updated Job Work Header

Revision ID: 2914f1fff07c
Revises: a460d8fb0ab0
Create Date: 2026-07-20 23:59:35.010233

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2914f1fff07c'
down_revision = 'a460d8fb0ab0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    

    with op.batch_alter_table('job_work_header', schema=None) as batch_op:
        batch_op.add_column(sa.Column('jobwork_no', sa.String(length=30), nullable=False))
        batch_op.add_column(sa.Column('output_item_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('planned_output_qty', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('job_work_cost', sa.Float(), nullable=True))
        batch_op.create_unique_constraint("uq_job_work_header_jobwork_no", ['jobwork_no'])
        batch_op.create_foreign_key("fk_jobwork_output_item", 'item_master', ['output_item_id'], ['id'])

    

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    

    with op.batch_alter_table('job_work_header', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('job_work_cost')
        batch_op.drop_column('planned_output_qty')
        batch_op.drop_column('output_item_id')
        batch_op.drop_column('jobwork_no')

    

    # ### end Alembic commands ###
