"""Added location to Sales Invoice Header

Revision ID: 38d705f9abb8
Revises: fc32f003eda3
Create Date: 2026-07-05 22:49:16.353418

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38d705f9abb8'
down_revision = 'fc32f003eda3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###


    with op.batch_alter_table('sales_invoice_header', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key("fk_sales_invoice_header_location", 'location_master', ['location_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sales_invoice_header', schema=None) as batch_op:
        batch_op.drop_constraint("fk_sales_invoice_header_location", type_='foreignkey')
        batch_op.drop_column('location_id')

    