"""add job work header

Revision ID: 38fc44031698
Revises: 6d1315ff4bc8
Create Date: 2026-07-20 23:14:12.341230

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38fc44031698'
down_revision = '6d1315ff4bc8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_work_header',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('jobwork_date', sa.Date(), nullable=False),
    sa.Column('vendor_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('remarks', sa.String(length=300), nullable=True),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendor_master.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    

    op.drop_table('job_work_header')
    # ### end Alembic commands ###
