"""Made expected return date optional in job work

Revision ID: 4254a03de5cf
Revises: 2914f1fff07c
Create Date: 2026-07-21 00:42:35.529278

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4254a03de5cf'
down_revision = '2914f1fff07c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    with op.batch_alter_table('job_work_header', schema=None) as batch_op:
        batch_op.alter_column('expected_return_date',
               existing_type=sa.DATE(),
               nullable=True)

    

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    with op.batch_alter_table('job_work_header', schema=None) as batch_op:
        batch_op.alter_column('expected_return_date',
               existing_type=sa.DATE(),
               nullable=False)

    
    # ### end Alembic commands ###
