"""Added inventory costing columns

Revision ID: 4c460fe1d24c
Revises: f28facbb0c7a
Create Date: 2026-07-14 00:29:15.133626

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c460fe1d24c'
down_revision = 'f28facbb0c7a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
