"""add recipe tables

Revision ID: 512866cce2eb
Revises: 4f21d9c8de1c
Create Date: 2026-06-21 22:08:17.629485

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '512866cce2eb'
down_revision = '4f21d9c8de1c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipe_header', schema=None) as batch_op:
        batch_op.add_column(sa.Column('recipe_name', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipe_header', schema=None) as batch_op:
        batch_op.drop_column('recipe_name')

    # ### end Alembic commands ###
