"""Added Receiving Note Header

Revision ID: 62434d92effe
Revises: 38d705f9abb8
Create Date: 2026-07-10 00:23:04.536088

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62434d92effe'
down_revision = '38d705f9abb8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('receiving_note_header',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rnote_no', sa.String(length=50), nullable=False),
    sa.Column('rnote_date', sa.Date(), nullable=False),
    sa.Column('sales_invoice_header_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('received_by', sa.String(length=150), nullable=True),
    sa.Column('remarks', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customer_master.id'], ),
    sa.ForeignKeyConstraint(['sales_invoice_header_id'], ['sales_invoice_header.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rnote_no')
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    op.drop_table('receiving_note_header')
    # ### end Alembic commands ###
