"""add production entry detail

Revision ID: 6b0b0f25e366
Revises: 75635f94f67b
Create Date: 2026-06-24 23:03:35.931283

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b0b0f25e366'
down_revision = '75635f94f67b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('production_entry_detail',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('production_entry_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('qty', sa.Float(), nullable=False),
    sa.Column('transaction_type', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['item_master.id'], ),
    sa.ForeignKeyConstraint(['production_entry_id'], ['production_entry.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('production_entry_detail')
    # ### end Alembic commands ###
