"""inventory transaction value

Revision ID: 6d1315ff4bc8
Revises: 94b2c1543d6b
Create Date: 2026-07-14 02:26:50.153842

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d1315ff4bc8'
down_revision = '94b2c1543d6b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    

    with op.batch_alter_table('inventory_ledger', schema=None) as batch_op:
        batch_op.add_column(sa.Column('transaction_value', sa.Float(), nullable=True))

    

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    

    with op.batch_alter_table('inventory_ledger', schema=None) as batch_op:
        batch_op.drop_column('transaction_value')

    

    # ### end Alembic commands ###
