"""add production entry

Revision ID: 75635f94f67b
Revises: 8afb5df5bf6b
Create Date: 2026-06-23 02:59:12.767673

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75635f94f67b'
down_revision = '8afb5df5bf6b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('production_entry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('production_date', sa.Date(), nullable=False),
    sa.Column('recipe_id', sa.Integer(), nullable=False),
    sa.Column('production_qty', sa.Float(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('remarks', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['location_id'], ['location_master.id'], ),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipe_header.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('production_entry')
    # ### end Alembic commands ###
