"""Recipe supports FG output but removed previous change

Revision ID: 78ac667b067e
Revises: b3d6421e9c97
Create Date: 2026-07-03 00:28:15.316565

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78ac667b067e'
down_revision = 'b3d6421e9c97'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipe_header', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_recipe_header_finished_good'), type_='foreignkey')
        batch_op.drop_column('output_finished_good_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipe_header', schema=None) as batch_op:
        batch_op.add_column(sa.Column('output_finished_good_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_recipe_header_finished_good'), 'finished_goods', ['output_finished_good_id'], ['id'])

    # ### end Alembic commands ###
