"""remove location and wage type

Revision ID: 7cad36f0c62f
Revises: 8969751c02d0
Create Date: 2026-07-24 21:39:59.623006

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7cad36f0c62f'
down_revision = '8969751c02d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    

    with op.batch_alter_table('item_master', schema=None) as batch_op:
        batch_op.drop_column('piece_rate')

    with op.batch_alter_table("labour_master") as batch_op:

        batch_op.drop_column("wage_type")

        batch_op.drop_column("location_id")

    

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    

    with op.batch_alter_table('labour_master', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location_id', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('wage_type', sa.VARCHAR(length=20), nullable=False))
        pass

    with op.batch_alter_table('item_master', schema=None) as batch_op:
        batch_op.add_column(sa.Column('piece_rate', sa.FLOAT(), nullable=True))