"""Add labour master and piece rate in Itemmaster

Revision ID: 8969751c02d0
Revises: b83510325e2f
Create Date: 2026-07-24 03:01:59.215180

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8969751c02d0'
down_revision = 'b83510325e2f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('labour_contractor_master',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contractor_code', sa.String(length=20), nullable=True),
    sa.Column('contractor_name', sa.String(length=200), nullable=False),
    sa.Column('contact_person', sa.String(length=100), nullable=True),
    sa.Column('mobile', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('gst_no', sa.String(length=30), nullable=True),
    sa.Column('pan_no', sa.String(length=20), nullable=True),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('contractor_code')
    )
    op.create_table('labour_type_master',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type_code', sa.String(length=20), nullable=False),
    sa.Column('type_name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('type_code')
    )
    op.create_table('labour_daily_sheet_header',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sheet_no', sa.String(length=30), nullable=False),
    sa.Column('sheet_date', sa.Date(), nullable=False),
    sa.Column('contractor_id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('remarks', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['contractor_id'], ['labour_contractor_master.id'], ),
    sa.ForeignKeyConstraint(['location_id'], ['location_master.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sheet_no')
    )
    op.create_table('labour_master',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('labour_code', sa.String(length=20), nullable=True),
    sa.Column('labour_name', sa.String(length=200), nullable=False),
    sa.Column('father_name', sa.String(length=200), nullable=True),
    sa.Column('gender', sa.String(length=10), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('blood_group', sa.String(length=10), nullable=True),
    sa.Column('aadhar_no', sa.String(length=20), nullable=True),
    sa.Column('mobile', sa.String(length=20), nullable=True),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('pincode', sa.String(length=20), nullable=True),
    sa.Column('labour_type_id', sa.Integer(), nullable=False),
    sa.Column('contractor_id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('wage_type', sa.String(length=20), nullable=False),
    sa.Column('daily_wage_rate', sa.Float(), nullable=True),
    sa.Column('contractor_rate', sa.Float(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['contractor_id'], ['labour_contractor_master.id'], ),
    sa.ForeignKeyConstraint(['labour_type_id'], ['labour_type_master.id'], ),
    sa.ForeignKeyConstraint(['location_id'], ['location_master.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('labour_code')
    )
    op.create_table('labour_daily_sheet_entry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sheet_id', sa.Integer(), nullable=False),
    sa.Column('labour_id', sa.Integer(), nullable=False),
    sa.Column('labour_type_id', sa.Integer(), nullable=False),
    sa.Column('time_in', sa.Time(), nullable=False),
    sa.Column('time_out', sa.Time(), nullable=False),
    sa.Column('break_hours', sa.Float(), nullable=True),
    sa.Column('total_hours', sa.Float(), nullable=True),
    sa.Column('wage_type', sa.String(length=20), nullable=False),
    sa.Column('daily_rate', sa.Float(), nullable=True),
    sa.Column('total_wages', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['labour_id'], ['labour_master.id'], ),
    sa.ForeignKeyConstraint(['labour_type_id'], ['labour_type_master.id'], ),
    sa.ForeignKeyConstraint(['sheet_id'], ['labour_daily_sheet_header.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('labour_daily_sheet_entry_detail',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entry_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('recipe_id', sa.Integer(), nullable=True),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('hours_worked', sa.Float(), nullable=True),
    sa.Column('qty_produced', sa.Float(), nullable=True),
    sa.Column('piece_rate', sa.Float(), nullable=True),
    sa.Column('piece_wages', sa.Float(), nullable=True),
    sa.Column('proportionate_wages', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['entry_id'], ['labour_daily_sheet_entry.id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['item_master.id'], ),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipe_header.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    
    with op.batch_alter_table('item_master', schema=None) as batch_op:
        batch_op.add_column(sa.Column('piece_rate', sa.Float(), nullable=True))

    

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    

    with op.batch_alter_table('item_master', schema=None) as batch_op:
        batch_op.drop_column('piece_rate')

    

    op.drop_table('labour_daily_sheet_entry_detail')
    op.drop_table('labour_daily_sheet_entry')
    op.drop_table('labour_master')
    op.drop_table('labour_daily_sheet_header')
    op.drop_table('labour_type_master')
    op.drop_table('labour_contractor_master')
    # ### end Alembic commands ###
