"""vendor code nullable

Revision ID: 8aca85ee91de
Revises: 5934b75a9c90
Create Date: 2026-06-28 18:21:44.330961

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8aca85ee91de'
down_revision = '5934b75a9c90'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vendor_master', schema=None) as batch_op:
        batch_op.alter_column('vendor_code',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vendor_master', schema=None) as batch_op:
        batch_op.alter_column('vendor_code',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)

    # ### end Alembic commands ###
