"""inventory costing engine

Revision ID: 94b2c1543d6b
Revises: 4c460fe1d24c
Create Date: 2026-07-14 01:16:19.029542

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94b2c1543d6b'
down_revision = '4c460fe1d24c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    

    with op.batch_alter_table('opening_stock_detail', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rate', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('value', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('opening_stock_detail', schema=None) as batch_op:
        batch_op.drop_column('value')
        batch_op.drop_column('rate')

   

    # ### end Alembic commands ###
