"""Added Customer Purchase Order

Revision ID: 9e3bc4a6aa8a
Revises: 71b70d49d8f7
Create Date: 2026-06-30 00:35:02.144412

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e3bc4a6aa8a'
down_revision = '71b70d49d8f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer_po_header',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('customer_po_no', sa.String(length=100), nullable=False),
    sa.Column('customer_po_date', sa.Date(), nullable=False),
    sa.Column('order_received_date', sa.Date(), nullable=False),
    sa.Column('payment_terms', sa.String(length=200), nullable=True),
    sa.Column('freight_terms', sa.String(length=200), nullable=True),
    sa.Column('remarks', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customer_master.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('customer_po_detail',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_po_header_id', sa.Integer(), nullable=False),
    sa.Column('line_no', sa.String(length=30), nullable=True),
    sa.Column('finished_good_id', sa.Integer(), nullable=False),
    sa.Column('qty', sa.Float(), nullable=False),
    sa.Column('rate', sa.Float(), nullable=True),
    sa.Column('freight', sa.Float(), nullable=True),
    sa.Column('gst_rate', sa.Float(), nullable=True),
    sa.Column('basic_amount', sa.Float(), nullable=True),
    sa.Column('gst_amount', sa.Float(), nullable=True),
    sa.Column('total_amount', sa.Float(), nullable=True),
    sa.Column('delivery_date', sa.Date(), nullable=True),
    sa.Column('produced_qty', sa.Float(), nullable=True),
    sa.Column('fg_qty', sa.Float(), nullable=True),
    sa.Column('dispatched_qty', sa.Float(), nullable=True),
    sa.Column('pending_qty', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['customer_po_header_id'], ['customer_po_header.id'], ),
    sa.ForeignKeyConstraint(['finished_good_id'], ['finished_goods.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('customer_po_detail')
    op.drop_table('customer_po_header')
    # ### end Alembic commands ###
