"""Added expected return date to Job Work Header

Revision ID: a460d8fb0ab0
Revises: 258c585a4081
Create Date: 2026-07-20 23:41:39.444727

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a460d8fb0ab0'
down_revision = '258c585a4081'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    

    with op.batch_alter_table('job_work_header', schema=None) as batch_op:
        batch_op.add_column(sa.Column('expected_return_date', sa.Date(), nullable=False))

    

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    

    with op.batch_alter_table('job_work_header', schema=None) as batch_op:
        batch_op.drop_column('expected_return_date')

    

    # ### end Alembic commands ###
