"""Added Job Work Ledger

Revision ID: a68b27308cfa
Revises: 0be85d51eb97
Create Date: 2026-07-22 23:33:53.926165

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a68b27308cfa'
down_revision = '0be85d51eb97'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_work_ledger',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_work_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('issued_qty', sa.Float(), nullable=True),
    sa.Column('received_qty', sa.Float(), nullable=True),
    sa.Column('balance_qty', sa.Float(), nullable=True),
    sa.Column('issued_rate', sa.Float(), nullable=True),
    sa.Column('issued_value', sa.Float(), nullable=True),
    sa.Column('line_type', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['item_master.id'], ),
    sa.ForeignKeyConstraint(['job_work_id'], ['job_work_header.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    

    op.drop_table('job_work_ledger')
    # ### end Alembic commands ###
