"""add plant and stage columns

Revision ID: a9b4630ff346
Revises: 
Create Date: 2026-06-21 01:25:46.860716

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a9b4630ff346'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item_master', schema=None) as batch_op:
        batch_op.add_column(sa.Column('production_stage', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item_master', schema=None) as batch_op:
        batch_op.drop_column('production_stage')

    # ### end Alembic commands ###
