"""Added Destination Master

Revision ID: ab102a10c482
Revises: 27087b17c8dd
Create Date: 2026-07-05 12:47:07.876116

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab102a10c482'
down_revision = '27087b17c8dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('destination_master',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('destination_name', sa.String(length=200), nullable=False),
    sa.Column('state_name', sa.String(length=100), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('destination_name')
    )
    op.drop_table('_alembic_tmp_customer_po_detail')
    with op.batch_alter_table('customer_po_detail', schema=None) as batch_op:
        batch_op.alter_column('item_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customer_po_detail', schema=None) as batch_op:
        batch_op.alter_column('item_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    op.create_table('_alembic_tmp_customer_po_detail',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('customer_po_header_id', sa.INTEGER(), nullable=False),
    sa.Column('line_no', sa.VARCHAR(length=30), nullable=True),
    sa.Column('qty', sa.FLOAT(), nullable=False),
    sa.Column('rate', sa.FLOAT(), nullable=True),
    sa.Column('freight', sa.FLOAT(), nullable=True),
    sa.Column('gst_rate', sa.FLOAT(), nullable=True),
    sa.Column('basic_amount', sa.FLOAT(), nullable=True),
    sa.Column('gst_amount', sa.FLOAT(), nullable=True),
    sa.Column('total_amount', sa.FLOAT(), nullable=True),
    sa.Column('delivery_date', sa.DATE(), nullable=True),
    sa.Column('produced_qty', sa.FLOAT(), nullable=True),
    sa.Column('fg_qty', sa.FLOAT(), nullable=True),
    sa.Column('dispatched_qty', sa.FLOAT(), nullable=True),
    sa.Column('pending_qty', sa.FLOAT(), nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), nullable=True),
    sa.Column('item_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['customer_po_header_id'], ['customer_po_header.id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['item_master.id'], name=op.f('fk_customer_po_detail_item')),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('destination_master')
    # ### end Alembic commands ###
