"""Added Destination Master

Revision ID: ab102a10c482
Revises: 27087b17c8dd
Create Date: 2026-07-05 12:47:07.876116

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab102a10c482'
down_revision = '27087b17c8dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('destination_master',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('destination_name', sa.String(length=200), nullable=False),
    sa.Column('state_name', sa.String(length=100), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('destination_name')
    )
    

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    op.drop_table('destination_master')
    # ### end Alembic commands ###
