"""Recipe supports FG output

Revision ID: b3d6421e9c97
Revises: 9e3bc4a6aa8a
Create Date: 2026-07-02 23:36:19.330532

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3d6421e9c97'
down_revision = '9e3bc4a6aa8a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipe_header', schema=None) as batch_op:
        batch_op.add_column(sa.Column('output_finished_good_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key("fk_recipe_header_finished_good", 'finished_goods', ['output_finished_good_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipe_header', schema=None) as batch_op:
        batch_op.drop_constraint("fk_recipe_header_finished_good", type_='foreignkey')
        batch_op.drop_column('output_finished_good_id')

    # ### end Alembic commands ###
