"""Fix job work cascade nullable

Revision ID: b83510325e2f
Revises: 4d74eb1ee511
Create Date: 2026-07-24 01:57:18.469582

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b83510325e2f'
down_revision = '4d74eb1ee511'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_job_work_header')
    

    

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    

    op.create_table('_alembic_tmp_job_work_header',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('jobwork_date', sa.DATE(), nullable=False),
    sa.Column('vendor_id', sa.INTEGER(), nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), nullable=True),
    sa.Column('remarks', sa.VARCHAR(length=300), nullable=True),
    sa.Column('expected_return_date', sa.DATE(), nullable=True),
    sa.Column('jobwork_no', sa.VARCHAR(length=30), nullable=False),
    sa.Column('output_item_id', sa.INTEGER(), nullable=False),
    sa.Column('planned_output_qty', sa.FLOAT(), nullable=True),
    sa.Column('job_work_cost', sa.FLOAT(), nullable=True),
    sa.Column('location_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['location_master.id'], name=op.f('fk_jw_header_location')),
    sa.ForeignKeyConstraint(['output_item_id'], ['item_master.id'], name=op.f('fk_jobwork_output_item')),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendor_master.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('jobwork_no', name=op.f('uq_job_work_header_jobwork_no'))
    )
    # ### end Alembic commands ###
