"""empty message

Revision ID: cd7ace2abab6
Revises: 7cad36f0c62f
Create Date: 2026-07-24 21:48:00.120599

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd7ace2abab6'
down_revision = '7cad36f0c62f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass

    

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass

    # ### end Alembic commands ###
