"""link item master to production stage

Revision ID: cf9fd5bc11ce
Revises: d5ec8a7388bd
Create Date: 2026-06-21 22:58:54.717896

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf9fd5bc11ce'
down_revision = 'd5ec8a7388bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item_master', schema=None) as batch_op:
        batch_op.add_column(sa.Column('production_stage_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(
    'fk_item_master_stage',
    'production_stage_master',
    ['production_stage_id'],
    ['id']
)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item_master', schema=None) as batch_op:
        batch_op.drop_constraint(
    'fk_item_master_stage',
    type_='foreignkey'
    )
        batch_op.drop_column('production_stage_id')

    # ### end Alembic commands ###
