"""add production stage master

Revision ID: d5ec8a7388bd
Revises: 512866cce2eb
Create Date: 2026-06-21 22:51:41.384546

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd5ec8a7388bd'
down_revision = '512866cce2eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('production_stage_master',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stage_no', sa.Integer(), nullable=False),
    sa.Column('stage_name', sa.String(length=100), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('production_stage_master')
    # ### end Alembic commands ###
