"""add opening stock

Revision ID: df5500c7cd08
Revises: 6b0b0f25e366
Create Date: 2026-06-27 00:48:15.315902

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df5500c7cd08'
down_revision = '6b0b0f25e366'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('opening_stock',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('opening_date', sa.Date(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('remarks', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['location_id'], ['location_master.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('opening_stock_detail',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('opening_stock_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('qty', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['item_master.id'], ),
    sa.ForeignKeyConstraint(['opening_stock_id'], ['opening_stock.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('opening_stock_detail')
    op.drop_table('opening_stock')
    # ### end Alembic commands ###
