"""updated payment module

Revision ID: e5e2be600b5a
Revises: e831c3758666
Create Date: 2026-07-12 12:26:46.885447

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5e2be600b5a'
down_revision = 'e831c3758666'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payment_receipt_header',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('payment_no', sa.String(length=50), nullable=False),
    sa.Column('payment_date', sa.Date(), nullable=False),
    sa.Column('bill_submission_header_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('sales_invoice_header_id', sa.Integer(), nullable=False),
    sa.Column('bill_amount', sa.Float(), nullable=True),
    sa.Column('amount_received', sa.Float(), nullable=True),
    sa.Column('tds_deducted', sa.Float(), nullable=True),
    sa.Column('ld_charges', sa.Float(), nullable=True),
    sa.Column('general_damage_charges', sa.Float(), nullable=True),
    sa.Column('other_deductions', sa.Float(), nullable=True),
    sa.Column('payment_mode', sa.String(length=30), nullable=True),
    sa.Column('bank_name', sa.String(length=100), nullable=True),
    sa.Column('utr_no', sa.String(length=100), nullable=True),
    sa.Column('remarks', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.ForeignKeyConstraint(['bill_submission_header_id'], ['bill_submission_header.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customer_master.id'], ),
    sa.ForeignKeyConstraint(['sales_invoice_header_id'], ['sales_invoice_header.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('payment_no')
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    op.drop_table('payment_receipt_header')
    # ### end Alembic commands ###
