"""Added Bill Submission

Revision ID: e831c3758666
Revises: 191c63f41e22
Create Date: 2026-07-10 20:50:16.871780

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e831c3758666'
down_revision = '191c63f41e22'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bill_submission_header',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bill_submission_no', sa.String(length=50), nullable=False),
    sa.Column('bill_submission_date', sa.Date(), nullable=False),
    sa.Column('receiving_note_header_id', sa.Integer(), nullable=False),
    sa.Column('sales_invoice_header_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('drr_no', sa.String(length=100), nullable=True),
    sa.Column('ro_no', sa.String(length=100), nullable=True),
    sa.Column('ro_date', sa.Date(), nullable=True),
    sa.Column('bill_amount', sa.Float(), nullable=True),
    sa.Column('remarks', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customer_master.id'], ),
    sa.ForeignKeyConstraint(['receiving_note_header_id'], ['receiving_note_header.id'], ),
    sa.ForeignKeyConstraint(['sales_invoice_header_id'], ['sales_invoice_header.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bill_submission_no')
    )
    op.create_table('bill_submission_detail',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bill_submission_header_id', sa.Integer(), nullable=False),
    sa.Column('receiving_note_detail_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('received_qty', sa.Float(), nullable=False),
    sa.Column('rate', sa.Float(), nullable=True),
    sa.Column('freight', sa.Float(), nullable=True),
    sa.Column('gst_rate', sa.Float(), nullable=True),
    sa.Column('basic_amount', sa.Float(), nullable=True),
    sa.Column('gst_amount', sa.Float(), nullable=True),
    sa.Column('total_amount', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['bill_submission_header_id'], ['bill_submission_header.id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['item_master.id'], ),
    sa.ForeignKeyConstraint(['receiving_note_detail_id'], ['receiving_note_detail.id'], ),
    sa.PrimaryKeyConstraint('id')
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    op.drop_table('bill_submission_detail')
    op.drop_table('bill_submission_header')
    # ### end Alembic commands ###
