"""add gst fields to item master

Revision ID: ec130b402adf
Revises: 0b3eafe3ce34
Create Date: 2026-06-28 18:56:43.859279

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec130b402adf'
down_revision = '0b3eafe3ce34'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item_master', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hsn_code', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('gst_rate', sa.Float(), nullable=True))

    with op.batch_alter_table('purchase_receipt_detail', schema=None) as batch_op:
        batch_op.add_column(sa.Column('basic_amount', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('gst_rate', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('gst_amount', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('invoice_amount', sa.Float(), nullable=True))
        batch_op.drop_column('amount')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('purchase_receipt_detail', schema=None) as batch_op:
        batch_op.add_column(sa.Column('amount', sa.FLOAT(), nullable=True))
        batch_op.drop_column('invoice_amount')
        batch_op.drop_column('gst_amount')
        batch_op.drop_column('gst_rate')
        batch_op.drop_column('basic_amount')

    with op.batch_alter_table('item_master', schema=None) as batch_op:
        batch_op.drop_column('gst_rate')
        batch_op.drop_column('hsn_code')

    # ### end Alembic commands ###
