"""remove payment mode

Revision ID: f28facbb0c7a
Revises: e5e2be600b5a
Create Date: 2026-07-12 13:33:37.190759

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f28facbb0c7a'
down_revision = 'e5e2be600b5a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    

    with op.batch_alter_table('payment_receipt_header', schema=None) as batch_op:
        batch_op.drop_column('payment_mode')
        batch_op.drop_column('bank_name')
        batch_op.drop_column('utr_no')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment_receipt_header', schema=None) as batch_op:
        batch_op.add_column(sa.Column('utr_no', sa.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('bank_name', sa.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('payment_mode', sa.VARCHAR(length=30), nullable=True))

    
    # ### end Alembic commands ###
