"""Added draft flag

Revision ID: f5e5bb936f56
Revises: 4254a03de5cf
Create Date: 2026-07-22 22:40:40.546941

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f5e5bb936f56'
down_revision = '4254a03de5cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    

    with op.batch_alter_table('job_work_header', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_draft', sa.Boolean(), server_default='1', nullable=False))

    

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    

    with op.batch_alter_table('job_work_header', schema=None) as batch_op:
        batch_op.drop_column('is_draft')

    

    # ### end Alembic commands ###
