"""add production stage to recipe header

Revision ID: f7599c8fb8a6
Revises: cf9fd5bc11ce
Create Date: 2026-06-22 00:05:57.416180

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f7599c8fb8a6'
down_revision = 'cf9fd5bc11ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipe_header', schema=None) as batch_op:
        batch_op.add_column(sa.Column('production_stage_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_recipe_header_stage', 'production_stage_master', ['production_stage_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipe_header', schema=None) as batch_op:
        batch_op.drop_constraint('fk_recipe_header_stage', type_='foreignkey')
        batch_op.drop_column('production_stage_id')

    # ### end Alembic commands ###
