"""Added Sales Invoice

Revision ID: fc32f003eda3
Revises: ab102a10c482
Create Date: 2026-07-05 15:10:05.681450

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc32f003eda3'
down_revision = 'ab102a10c482'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sales_invoice_header',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('invoice_no', sa.String(length=50), nullable=False),
    sa.Column('invoice_date', sa.Date(), nullable=False),
    sa.Column('customer_po_header_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('destination_id', sa.Integer(), nullable=False),
    sa.Column('transporter_id', sa.Integer(), nullable=False),
    sa.Column('vehicle_no', sa.String(length=50), nullable=True),
    sa.Column('lr_no', sa.String(length=100), nullable=True),
    sa.Column('eway_bill_no', sa.String(length=100), nullable=True),
    sa.Column('remarks', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customer_master.id'], ),
    sa.ForeignKeyConstraint(['customer_po_header_id'], ['customer_po_header.id'], ),
    sa.ForeignKeyConstraint(['destination_id'], ['destination_master.id'], ),
    sa.ForeignKeyConstraint(['transporter_id'], ['transporter_master.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('invoice_no')
    )
    op.create_table('sales_invoice_detail',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sales_invoice_header_id', sa.Integer(), nullable=False),
    sa.Column('customer_po_detail_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('dispatch_qty', sa.Float(), nullable=False),
    sa.Column('rate', sa.Float(), nullable=True),
    sa.Column('freight', sa.Float(), nullable=True),
    sa.Column('gst_rate', sa.Float(), nullable=True),
    sa.Column('basic_amount', sa.Float(), nullable=True),
    sa.Column('gst_amount', sa.Float(), nullable=True),
    sa.Column('total_amount', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['customer_po_detail_id'], ['customer_po_detail.id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['item_master.id'], ),
    sa.ForeignKeyConstraint(['sales_invoice_header_id'], ['sales_invoice_header.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    op.drop_table('sales_invoice_detail')
    op.drop_table('sales_invoice_header')
    # ### end Alembic commands ###
